# Generated by Django 5.0.6 on 2024-07-13 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_chatroomname_alter_chatroom_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMssg', models.TextField(default='', max_length=1000)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('isRecieved', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('seenAt', models.DateTimeField(default=None)),
                ('sendBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chats',
            field=models.ManyToManyField(default=None, to='chat.chats'),
        ),
    ]
