# Generated by Django 5.0.6 on 2024-07-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chats_chatroom_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='isRecieved',
        ),
    ]
