# Generated by Django 5.0.6 on 2024-07-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chats_isrecieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='seenAt',
            field=models.DateTimeField(null=True),
        ),
    ]
