# Generated by Django 5.0.6 on 2024-07-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chats_seenat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['-timeStamp']},
        ),
    ]
